version: "3"

services:

  app:
    container_name: notification
    build: ./

    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notification
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: